version: '3'
services:
  db:
    image: docker.io/postgres:15.1
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "avva"
      POSTGRES_PASSWORD: "avva"
  redis:
    image: docker.io/redis:7.0
    ports:
      - "6379:6379"
  # web:
  #   build: .
  #   command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #     - redis
  #   env_file:
  #     - .env
  adminer:
    image: docker.io/adminer:4.8.1
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

